env:
  browser: true
  es6: true
extends:
  - 'plugin:vue/essential'
  - "@vue/airbnb"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  parser: "babel-eslint"
plugins:
  - vue
rules:
  "comma-dangle": 0
  "no-console": 0
  "no-plusplus": 0
  "max-len": 0


