swagger: '2.0'
basePath: /api
info:
  title: Estimation Game API
  version: "0.1"
  description: Simpe Restful API for the estimation game app
consumes:
  - application/json
produces:
  - application/json




paths:
  /ping:
    get:
      operationId: app.ping_pong
      summary: Do a ping, get a pong
      responses:
        200:
          description: Pong
          schema:
            type: string
            example: "Pong"
  /hello:
    get:
      operationId: app.hello
      summary: Like a ping but with attached session
      responses:
        200:
          description: Pong
          schema:
            type: string
            example: "Total visits: 42"
  /story:
    get:
      tags: [ Story ]
      operationId: app.get_story
      summary: Get the story
      responses:
        200:
          description: Return the story that is to be estimated
          schema:
            type: object
            $ref: '#/definitions/Story'
    put:
      tags: [ Story ]
      operationId: app.put_story
      summary: Modify the story
      consumes:
        - application/json
      parameters:
        - in: body
          name: story
          description: The story to update.
          schema:
            type: object
            properties:
              title:
                type: string
                example: "[BACKEND-42] Develop new feature"
              description:
                type: string
                example: "Because the customer is in desperate need"
      responses:
        200:
          description: Return the story that is to be estimated
          schema:
            type: object
            $ref: '#/definitions/Story'

definitions:
  Story:
    type: object
    required:
      - title
      - description
    properties:
      title:
        type: string
        description: Short title, probably containing ticket number
        example: "[BACKEND-42] Develop new feature"
        minLength: 1
        maxLength: 100
      description:
        type: string
        description: The long story description
        example: "Because the customer is in desperate need"
        minLength: 1
