version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    network_mode: "bridge"
    volumes:
      - ./html/:/usr/share/nginx/html/
#      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/:/etc/nginx/conf.d/
    ports:
      - 8000:80
#    environment:
#      - HOST_UPSTREAM=http://${DOCKER_GATEWAY_HOST:-xxx}:5000