version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    network_mode: "bridge"
    volumes:
      - ./html/:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_params:/etc/nginx/proxy_params
    ports:
      - 8000:80
