name: Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:        
        description: 'The version tag that is to be released'                        
        required: true

jobs:
  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Perform nmp run build
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: make release      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: pre-release
          tag_name: ${{ github.ref }}          
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./estimo.tar.gz
          asset_name: estimo.tar.gz
          asset_content_type: application/gzip          
          
          
          
